# tests/testthat/test-snapshot-baseline.R
#
# PURPOSE: Regression tests comparing current pipeline output against saved
# snapshots. These tests detect silent changes in numerical results.
#
# Requirements:
#   - Snapshots generated by: source("tests/testdata/generate_snapshots.R")
#   - PIPAPI_DATA_ROOT_FOLDER_LOCAL env var set
#
# Run snapshot tests only:
#   devtools::test(filter = "snapshot")

snap_dir <- testthat::test_path("../testdata/snapshots")
data_dir <- Sys.getenv("PIPAPI_DATA_ROOT_FOLDER_LOCAL")

skip_if(
  !dir.exists(snap_dir) || length(list.files(snap_dir, "*.rds")) == 0,
  "Snapshots not found. Run tests/testdata/generate_snapshots.R first."
)
skip_if(
  data_dir == "",
  "PIPAPI_DATA_ROOT_FOLDER_LOCAL is not set."
)

# --- Setup -------------------------------------------------------------------

lkups <- create_versioned_lkups(data_dir = fs::path(data_dir))
lkup <- lkups$versions_paths[[lkups$latest_release]]

load_snap <- function(name) {
  path <- file.path(snap_dir, paste0(name, ".rds"))
  skip_if(!file.exists(path), paste("Snapshot not found:", name))
  readRDS(path)
}

# --- Tests -------------------------------------------------------------------

test_that("pip AGO 2000 matches snapshot", {
  expected <- load_snap("snap_pip_ago_2000")
  actual <- pip("AGO", year = 2000, povline = 1.9, lkup = lkup)
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip AGO all years matches snapshot", {
  expected <- load_snap("snap_pip_ago_all")
  actual <- pip("AGO", year = "ALL", povline = 1.9, lkup = lkup)
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip AGO fill-gaps matches snapshot", {
  expected <- load_snap("snap_pip_ago_fg")
  actual <- pip(
    "AGO",
    year = "ALL",
    povline = 1.9,
    fill_gaps = TRUE,
    lkup = lkup
  )
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip ALL 2015 matches snapshot", {
  expected <- load_snap("snap_pip_all_2015")
  actual <- pip("ALL", year = 2015, povline = 1.9, lkup = lkup)
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip CHN 2018 all reporting levels matches snapshot", {
  expected <- load_snap("snap_pip_chn_2018")
  actual <- pip(
    "CHN",
    year = 2018,
    povline = 1.9,
    reporting_level = "all",
    lkup = lkup
  )
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip_agg ALL 2015 wb matches snapshot", {
  expected <- load_snap("snap_agg_all_2015")
  actual <- pip_agg(
    "ALL",
    year = 2015,
    povline = 1.9,
    group_by = "wb",
    lkup = lkup
  )
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip AGO 2000 multiple poverty lines matches snapshot", {
  expected <- load_snap("snap_pip_ago_multi_pl")
  actual <- pip("AGO", year = 2000, povline = c(1.9, 3.65, 6.85), lkup = lkup)
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip AGO 2000 popshare matches snapshot", {
  expected <- load_snap("snap_pip_ago_popshare")
  actual <- pip("AGO", year = 2000, popshare = 0.2, lkup = lkup)
  expect_equal(actual, expected, tolerance = 1e-10)
})

test_that("pip ALL all years global poverty matches snapshot", {
  expected <- load_snap("snap_pip_wld_pov")
  actual <- pip("ALL", year = "ALL", povline = 3, lkup = lkup)
  expect_equal(actual, expected, tolerance = 1e-10)
})
