openapi: 3.0.0
info:
  description: This API computes all poverty and inequality statistics available at pip.worldbank.org
  title: Poverty and Inequality Platform API
  version: 0.0.1
paths:
  /api/v1/health-check:
    get:
      summary: ' Determine if the API is running and listening as expected'
      responses:
        default:
          description: Default response.
      parameters: []
  /api/v1/versions:
    get:
      summary: ' Return available data versions'
      responses:
        default:
          description: Default response.
      parameters:
          - in: query
            name: format
            schema:
              type: string
              enum: [json, csv, rds]
            description: Response format. Defaults to json.
  /api/v1/pip-info:
    get:
      summary: ' Return information about the API'
      responses:
        default:
          description: Default response.
      parameters: []
  /api/v1/valid-params:
    get:
      summary: ' Return valid query parameters'
      responses:
        default:
          description: Default response.
      parameters:
          - in: query
            name: endpoint
            schema:
              type: string
              enum: [aux, pip, pip-grp, pip-info, valid-params, all]
            description: Endpoint for which corresponding valid parameters will be returned
          - in: query
            name: version
            schema:
              type: string
            description: Data version. Defaults to most recent version. See api/v1/versions.
          - in: query
            name: format
            schema:
              type: string
              enum: [json, csv, rds]
            description: Response format. Defaults to json.
  /api/v1/aux:
    get:
      summary: ' Return auxiliary data tables'
      responses:
        default:
          description: Default response.
      parameters:
          - in: query
            name: table
            schema:
              type: string
            description: Auxiliary data table to be returned.
          - in: query
            name: version
            schema:
              type: string
            description: Data version. Defaults to most recent version. See api/v1/versions.
          - in: query
            name: format
            schema:
              type: string
              enum: [json, csv, rds]
            description: Response format. Defaults to json.
  /api/v1/pip:
    get:
      summary: ' Return main poverty and inequality statistics'
      description: Main function to compute poverty and inequality statistics.
      parameters:
           - in: query
             name: country
             required: true
             schema:
              type: array
              items:
               type: string
               enum: [AGO, ALB, COL, SSA, all]
               example: AGO
             description: The countries for which statistics are to be computed, specified as ISO3 codes.
           - in: query
             name: year
             required: true
             schema:
              type: array
              items:
               type: string
               enum: [2008, 2018, all]
               example: 2008
             description: Year(s) for which statistics are to be computed, specified as YYYY.
           - in: query
             name: povline
             schema:
              type: number
              minimum: 0
              maximum: 10000
              example: 1.90
             description: Poverty line to be used to compute poverty mesures.
           - in: query
             name: popshare
             schema:
              type: number
              minimum: 0
              maximum: 1
             description: Proportion of the population living below the poverty line. Will be ignored if povline is specified.
           - in: query
             name: fill_gaps
             schema:
              type: boolean
              example: FALSE
             description: Whether to interpolate / extrapolate statistics for years without available survey data.
           - in: query
             name: welfare_type
             schema:
              type: string
              enum: [all, consumption, income]
             description: Welfare measure
           - in: query
             name: reporting_level
             schema:
              type: string
              enum: [all, national, rural, urban]
             description: Reporting coverage.
           - in: query
             name: version
             schema:
              type: string
             description: Data version. Defaults to most recent version. See api/v1/versions.
           - in: query
             name: format
             schema:
              type: string
              enum: [json, csv, rds]
             description: Response format. Defaults to json.
      responses:
       '200':
         description: successful message
  /api/v1/pip-grp:
    get:
      summary: ' Return aggregations of PIP statistics'
      description: Compute aggregated poverty and inequality statistics
      parameters:
           - in: query
             name: country
             required: true
             schema:
              type: array
              items:
               type: string
               enum: [AGO, ALB, COL, all]
               example: all
             description: The countries for which statistics are to be computed, specified as ISO3 codes.
           - in: query
             name: year
             required: true
             schema:
              type: array
              items:
               type: string
               enum: [2008, 2018, all]
               example: 2018
             description: Year(s) for which statistics are to be computed, specified as YYYY.
           - in: query
             name: povline
             schema:
              type: number
              minimum: 0
              maximum: 10000
              example: 1.90
             description: Poverty line to be used to compute poverty mesures.
           - in: query
             name: popshare
             schema:
              type: number
              minimum: 0
              maximum: 1
             description: Proportion of the population living below the poverty line. Will be ignored if povline is specified.
           - in: query
             name: group_by
             schema:
              type: string
              enum: [none, wb]
              example: wb
             description: Aggregate results by pre-defined sub-groups.
           - in: query
             name: welfare_type
             schema:
              type: string
              enum: [all, consumption, income]
             description: Welfare measure
           - in: query
             name: reporting_level
             schema:
              type: string
              enum: [all, national]
             description: Reporting coverage.
           - in: query
             name: version
             schema:
              type: string
             description: Data version. Defaults to most recent version. See api/v1/versions.
           - in: query
             name: format
             schema:
              type: string
              enum: [json, csv, rds]
             description: Response format. Defaults to json.
      responses:
       '200':
         description: successful message
